function Im0(T, R) {
  return {
    ...T,
    ...R,
    bg: R.bg ?? T.bg,
    dim: R.dim ?? T.dim
  };
}
function $m0(T) {
  let R = T.split(".").pop()?.toLowerCase() || "";
  return {
    js: "javascript",
    jsx: "javascript",
    mjs: "javascript",
    cjs: "javascript",
    javascript: "javascript",
    ts: "typescript",
    tsx: "typescript",
    typescript: "typescript",
    py: "python",
    pyw: "python",
    python: "python",
    java: "java",
    c: "c",
    h: "c",
    cc: "cpp",
    cpp: "cpp",
    cxx: "cpp",
    "c++": "cpp",
    hpp: "cpp",
    hh: "cpp",
    hxx: "cpp",
    cs: "csharp",
    csharp: "csharp",
    go: "go",
    golang: "go",
    rs: "rust",
    rust: "rust",
    rb: "ruby",
    ruby: "ruby",
    php: "php",
    swift: "swift",
    kt: "kotlin",
    kts: "kotlin",
    kotlin: "kotlin",
    dart: "dart",
    sh: "bash",
    bash: "bash",
    zsh: "bash",
    shell: "bash",
    sql: "sql",
    json: "json",
    yaml: "yaml",
    yml: "yaml",
    md: "markdown",
    markdown: "markdown",
    zig: "zig",
    pas: "pascal",
    pascal: "pascal",
    html: "markup",
    htm: "markup",
    xml: "markup",
    svg: "markup",
    markup: "markup",
    css: "css"
  }[R] || "plain";
}