function GgT(T) {
  return T.replace(/\s+/g, " ").trim().replace(/\b(SELECT|FROM|WHERE|GROUP BY|ORDER BY|HAVING|LIMIT|JOIN|LEFT JOIN|RIGHT JOIN|INNER JOIN|OUTER JOIN|CROSS JOIN|ON|AND|OR|UNION|INTERSECT|EXCEPT|WITH|INSERT|UPDATE|DELETE|SET|VALUES|INTO)\b/gi, `
$1`).trim();
}