// === THREAD POOL SERVICE (gZR) ===
class gZR{placeholderThreadID;recentThreadIDsSubject=new j0([]);threadTitlesSubject=new j0({});threadHandlesSubject;allConnectedThreadActivityStatusesSubject=new j0({});legacyHandoffNavigationSubject=new H0;initializationStatusSubject=new j0({pending:!0,message:QpR});pendingApprovalsSubject=new j0([]);pendingSkillsSubject=new j0([]);attachedPool=null;attachedPoolSubscriptions=[];attached=!1;readyPromise;readyResolve=null;readyReject=null;constructor(R=jt()){this.placeholderThreadID=R;let T=new j0(jM0(this.placeholderThreadID)),a=new j0(new Map),e=new j0(t3R(T.getValue(),{state:"active",inferenceState:"idle",fileChanges:{files:[]}}));this.threadHandlesSubject=new j0(ZrR({thread$:T,threadViewState$:e,toolProgressByToolUseID$:a,pendingApprovals$:this.pendingApprovalsSubject,pendingSkills$:this.pendingSkillsSubject,getCurrentThread:()=>T.getValue(),sendMessage:async(r)=>(await this.waitForActiveHandle()).sendMessage(r),restoreTo:async(r)=>(await this.waitForActiveHandle()).restoreTo(r),queueMessage:async(r)=>(await this.waitForActiveHandle()).queueMessage(r),discardQueuedMessages:async()=>(await this.waitForActiveHandle()).discardQueuedMessages(),setTitle:async(r)=>(await this.waitForActiveHandle()).setTitle(r),setVisibility:async(r)=>(await this.waitForActiveHandle()).setVisibility(r),cancelTurn:async()=>(await this.waitForActiveHandle()).cancelTurn(),cancelStreaming:async()=>(await this.waitForActiveHandle()).cancelStreaming(),retryTurn:async()=>(await this.waitForActiveHandle()).retryTurn(),dismissEphemeralError:()=>{},preExecuteMode:async()=>(await this.waitForActiveHandle()).preExecuteMode?.(),postExecuteMode:async()=>(await this.waitForActiveHandle()).postExecuteMode?.(),resolveApproval:async(r,h,t)=>(await this.waitForActiveHandle()).resolveApproval(r,h,t),addPendingSkill:()=>{},removePendingSkill:()=>{},clearPendingSkills:()=>{},getDraft:async()=>(await this.waitForActiveHandle()).getDraft(),setDraft:async(r)=>(await this.waitForActiveHandle()).setDraft(r),getFilesAffectedByTruncation:async(r)=>(await this.waitForActiveHandle()).getFilesAffectedByTruncation(r),clearPendingNavigation:async()=>(await this.waitForActiveHandle()).clearPendingNavigation(),getGuidanceFiles:async(r)=>(await this.waitForActiveHandle()).getGuidanceFiles(r)})),this.readyPromise=new Promise((r,h)=>{this.readyResolve=r,this.readyReject=h}),this.readyPromise.catch(()=>{return})}get recentThreadIDs$(){return this.recentThreadIDsSubject}get threadTitles$(){return this.threadTitlesSubject}get threadHandles$(){return this.threadHandlesSubject}get legacyHandoffNavigation$(){return this.legacyHandoffNavigationSubject}get allConnectedThreadActivityStatuses$(){return this.allConnectedThreadActivityStatusesSubject}get initializationStatus$(){return this.initializationStatusSubject}get queueOnSubmitByDefault(){return this.attachedPool?.queueOnSubmitByDefault??!1}hasPendingInitialization(){return this.attachedPool===null}isDTWMode(){return this.attachedPool?.isDTWMode?.()===!0}isThr


// === createThread ===
async createThread(R,T){let a=T?.newThreadID??jt(),e=T?.agentMode,r=!1;if(T?.seededMessages)await this.seedThreadMessages(R,a,T.seededMessages,e),r=!0;let h=await this.createThreadWorker(R,a);if(h.thread.messages.length>0&&!r)return Z.info("createThread called for existing thread, returning existing worker",{threadID:a,messageCount:h.thread.messages.length}),{threadID:a,worker:h};if(e&&!r)await h.handle({type:"agent-mode",mode:e});if(T?.parent)await this.applyParentRelationship(R,h,a,T.parent),await this.inheritVisibilityIfNeeded(R,T.parent,a);if(T?.initialUserMessage){if(r)throw Error("initialUserMessage cannot be set when seededMessages is provided");await this.sendInitialUserMessage(h,T.initialUserMessage)}if(T?.draftContent){if(r)throw Error("draftContent cannot be set when seededMessages is provided");await this.setDraftContent(h,T.draftContent)}if(T?.navigate&&T?.parent)await this.setPendingNavigation(T.parent.threadID,a);if(T?.queuedMessages)await this.transferQueuedMessages(h,T.queuedMessages);return{threadID:a,worker:h}}async handoff(R,T){let a=await this.createThreadWorker(R,T.threadID),e=a.thread,r=T.images??[],h=T.signal??new AbortController().signal,{content:t}=await kET({thread:e,goal:T.goal,images:r,deps:{configService:R.configService,buildSystemPromptDeps:T.buildSystemPromptDeps,signal:h,filesystem:T.filesystem,deadline:T.deadline}}),i=typeof t==="string"?t:t.filter((C)=>C.type==="text"||C.type==="image"),c={threadID:T.threadID,type:"handoff",messageIndex:T.me


// === switchThread ===
null}getCompactionStatus(){let R=this.activeProvider;if(!R)return;return{compactionState:R.getCompactionState()}}async createThread(R){await this.activateThreadWithNavigation(R,{recordNavigation:!0})}async switchThread(R){await this.activateThreadWithNavigation(R,{recordNavigation:!0})}canNavigateBack(){return this.threadBackStack.length>0}canNavigateForward(){return this.threadForwardStack.length>0}async navigateBack(){if(!this.canNavigateBack())return;let R=this.activeThreadContextID;if(!R)return;let T=this.threadBackStack.pop();if(!T)return;this.threadForwardStack.push(R);try{await this.activateThreadWithNavigation(T,{recordNavigation:!1})}catch(a){throw this.threadForwardStack.pop(),this.threadBackStack.push(T),a}}async navigateForward(){if(!this.canNavigateForward())return;let R=this.activeThreadContextID;if(!R)return;let T=this.threadForwardStack.pop();if(!T)return;this.threadBackStack.push(R);try{await this.activateThreadWithNavigation(T,{recordNavigation:!1})}catch(a){throw thi


// === threadTitle @920596 ===
d to re-evaluate blocked tool",{error:T,toolUseID:R})}}ops={tools:{},toolMessages:{},inference:null,titleGeneration:null};_state=new j0("initial");state=this._state.pipe(f9(),k3({shouldCountRefs:!0}));handleMutex=new fu;ephemeralError=new j0(void 0);ephemeralErrorRetryAttempt=0;retryCountdownSeconds=new j0(void 0);retryTimer=null;retrySession=0;_inferenceState=new j0("idle");_turnStartTime=new j0(void 0);_turnElapsedMs=new j0(void 0);fileChanges=new j0({files:[]});get inferenceState(){return this._inferenceState.getValue()}toolCallUpdates=new H0;trackedFiles=new Mo;discoveredGuidanceFileURIs=n


// === threadTitle @925827 ===
ead:truncate",fromIndex:this.thread.messages.length-1});if(this.trackFilesFromHistory(),this.triggerTitleGeneration(),!this.shouldResumeFromLastMessage(R))return;await this.toolOrchestrator.onResume(),this.setupSettingsChangeHandlers(),this.setupEphemeralErrorLogging(),this.replayLastCompleteMessage()}resumed=!1;shouldResumeFromLastMessage(R){if(mnT(R)||fnT(R)&&!this.shouldContinueAfterRejection||RPR(R))return this._inferenceState.next("cancelled"),!1;return!0}replayLastCompleteMessage(){let R=this.thread.messages.findLastIndex((a)=>a.role==="user"?PnT(a):a.role==="assistant"&&a.state.type==="


// === threadTitle @938279 ===
erMessage}]}}).catch((T)=>{Z.debug("Failed to handle plugin agent.end continue",{error:T})})}triggerTitleGeneration(){if(this.thread.mainThreadID!==void 0||this.thread.title)return;this.ops.titleGeneration?.abort(),this.ops.titleGeneration=new AbortController;let R=this.ops.titleGeneration.signal;this.getConfig(R).then((T)=>{if(R.aborted)return;let a=T.settings?.["agent.skipTitleGenerationIfMessageContains"],e=Array.isArray(a)?a.filter((h)=>typeof h==="string"):[],r=this.thread.messages.find((h)=>{if(h.role!=="user")return!1;let t=bh(h.content);if(!t)return!1;if(e.length===0)return!0;return!e.


// === MESSAGE QUEUE ===
.toolOrchestrator.onAssistantMessageComplete(R.message)}).catch((e)=>{Z.error("onAssistantMessageComplete failed",{name:"ThreadWorker.handleDelta",threadID:this.threadID,messageState:R.message.state.type,error:e instanceof Error?e.message:String(e)})})}break}case"assistant:message-update":break;case"user:message-queue:enqueue":{let a=this._inferenceState.getValue();if(wNR(this.thread,a)!=="tool-running"){if(a==="cancelled"){this.handle({type:"user:message-queue:dequeue"});break}else if(a==="idle"){let e=this.thread.messages.at(-1);if(e?.role==="assistant"){if(e.state.type==="cancelled"||e.state.type==="error"){this.handle({type:"user:message-queue:dequeue"});break}if(e.state.type==="complete"&&e.state.stopReason!=="tool_use"){this.handle({type:"user:message-queue:dequeue"});break}}else if(e?.role==="info"){this.handle({type:"user:message-queue:dequeue"});break}}}break}case"info:manual-ba


// === DEQUEUE ===
rtAgentSpan(a),this.runInferenceAndUpdateThread({agentStart:{messageId:a,messageText:e}});break}case"user:message-queue:dequeue":{let a=this.thread.messages.at(-1);if(!a)break;if(a.role!=="user")break;this._turnStartTime.next(Date.now()),this._turnElapsedMs.next(void 0),this.trackFiles(a.fileMentions?.files?.map((h)=>h.uri).filter((h)=>h!==void 0)??[]);let e=a.messageId??0,r=bh(a.content);this.startAgentSpan(e),this.runInferenceAndUpdateThread({agentStart:{messageId:e,messageText:r}});break}case"user:tool-input":{this.toolOrchestrator.userProvideInput(R.toolUse,R.value).catch((a)=>{Z.error("userProvideInput failed",{name:"ThreadWorker.handleDelta",threadID:this.threadID,toolUse:R.toolUse,error:a instanceof Error?a.message:String(a)})});break}case"tool:data":{if(this.toolOrchestrator.isCancelled(R.toolUse)){let e=rC(this.thread).get(R.toolUse)?.run,r=e?q7(e):void 0;this.updateThread({type


// === COMPACTION STATUS ===
turn;return this.attachedPool.getTransportConnectionState()}getTransportConnectionRole(){if(!this.attachedPool?.getTransportConnectionRole)return;return this.attachedPool.getTransportConnectionRole()}getCompactionStatus(){if(!this.attachedPool?.getCompactionStatus)return;return this.attachedPool.getCompactionStatus()}attach(R){if(this.attached)throw Error("DeferredThreadPool is already attached");this.attached=!0,this.attachedPool=R;let T=null,a=null;this.attachedPoolSubscriptions=[R.recentThreadIDs$.subscribe((e)=>this.recentThreadIDsSubject.next(e)),R.threadTitles$.subscribe((e)=>this.threadTitlesSubject.next(e)),R.allConnectedThreadActivityStatuses$.subscribe((e)=>this.allConnectedThreadActivityStatusesSubject.next(e)),...R.legacyHandoffNavigation$?[R.legacyHandoffNavigation$.subscribe((e)=>{this.legacyHandoffNavigationSubject.next(e)})]:[],...R.initializationStatus$?[R.initializationStatus$.subscribe((e)=>this.initializationStatusSubject.next(e))]:[(()=>{return this.initializationS


// === HANDOFF STATE ===
ephemeralError=new j0(void 0);ephemeralErrorRetryAttempt=0;retryCountdownSeconds=new j0(void 0);retryTimer=null;retrySession=0;_inferenceState=new j0("idle");_turnStartTime=new j0(void 0);_turnElapsedMs=new j0(void 0);fileChanges=new j0({files:[]});get inferenceState(){return this._inferenceState.getValue()}toolCallUpdates=new H0;trackedFiles=new Mo;discoveredGuidanceFileURIs=new Set;fs;cachedFileChanges=[];disposed$=new H0;isDisposed=!1;shouldContinueAfterRejection=!1;_pendingSkills=new j0([]);handoffState=new j0(void 0);pendingSkills=this._pendingSkills.pipe(f9(),k3({shouldCountRefs:!0}));_awaitingSkillInvocation=new j0([]);toolOrchestrator;currentAgentSpan=null;currentSpan=null;traceStore;constructor(R,T){this.deps=R,this.threadID=T,this.fs=E3R({fileChangeTrackerStorage:this.deps.fileChangeTrackerStorage},this.deps.osFileSystem,T),this.traceStore={startTrace:(a)=>{this.updateThread({type:"trace:start",span:a})},recordTraceEvent:(a,e)=>{this.updateThread({type:"trace:event",span:a,event:e})},recordTraceAttributes:(a,e)=>{this.updateThread({type:"trace:attributes",span:a,attributes:e})},endTrace:(a)=>{this.updateThread({type:"trace:end",span:a})}},this.toolOrchestrator=new oWR(T,R.toolService,this.createOrchestratorCallbacks())}createTracer(R){return DLR(this.traceStore,R)}getPluginTracer(){let R=this.currentSpan?.id??this.currentAgentSpan?.span;if(!R)return;return this.createTracer(R)}createOrchestratorCallbacks(){return{getThread:()=>this.thread,updateThread:(R)=>this.updateThread(R),handle:(R,T)=>this.handle(R,T),getToolRunEnvironment:(R,T)=>this.getToolRunEnvironment(R,T),getHooks:async()=>(await this.getConfig()).settings?.hooks,getConfig:()=>this.getConfig(),updateFileChanges:()=>this.updateFileChanges(),trackFiles:(R)=>this.trackFiles(R),isDisposed:()=>this.isDisposed,getDisposed$:()=>this.disposed$,onSkillToolComplete:(R)=>this.onSkillToolComplete(R),applyHookResult:(R)=>Promise.resolve(Ps(this,R)),applyPostHookResult:(R,T)=>Promise.resolve(Ps(this,R,T)),re


// === HANDOFF MODE UI STATE ===
ull;newsFeedEntries=[];newsFeedSubscription=null;bottomGridUserHeight=void 0;bottomGridDragStartY=null;bottomGridDragStartHeight=null;previousThreadIdForHint=null;handoffController=null;handoffState={isInHandoffMode:!1,isGeneratingHandoff:!1,isConfirmingAbortHandoff:!1,pendingHandoffPrompt:null,spinner:null,countdownSeconds:null};isInQueueMode=!1;pendingMCPServers=[];mcpTrustSubscription=null;pendingOAuthRequest=null;pendingAuthLogin=null;authStatus="pending";authStatusSubscription=null;authModalKeyInterceptorUnsubscribe=null;queuedInterjectKeyInterceptorUnsubscribe=null;isCreatingAuthLoginSession=!1;queuedPromptAfterAuth=null;pendingInputDialog=null;pendingConfirmDialog=null;mcpServers=[];mcpServersSubscription=null;pluginInfos=[];pluginInfosSubscription=null;agentModeController;prospectiveAgentMode=null;freeTierStatus={canUseAmpFree:!1,isDailyGrantEnabled:!1};agentModePulseSeq=0;lastEffectiveAgentMode="smart";deepModeEffortHintController=new fJR({getDeepReasoningEffort:()=>this.deepReasoningEffort,getEffectiveAgentMode:()=>this.getEffectiveAgentMode(),canShowHintInCurrentThread:()=>this.widget.dependencies.activeThreadHandle.isThreadEmpty(),requestRender:()=>{if(!this.mounted)return;this.setState(()=>{})},isMounted:()=>this.mounted});updateState="hidden";updateServiceSubscription=null;toastController=new x1R;isMessageViewInSelectionMode=!1;isShowingForkDeprecationModal=!1;mysteriousMessage=null;isShowingMysteriousMessageModal=!1;mysteriousMessageSubscription=null;mysterySequenceManager=null;mysterySequenceProgress=null;mysteryKeyInterceptorUnsubscribe=null;static MYSTERY_SEQUENCE=["ctrl+x","y","z"];splashOrbExplosion=null;splashOrbExplosionSeq=0;freeTierStatusSubscription=null;allConnectedThreadActivityStatusesSubscription=null;threadInitializationStatusSubscription=null;allConnectedThreadActivityStatuses={};threadInitializationMessage=null;threadTitlesSubscription=null;threadTitles={};activeThreadSubscription=null;legacyHandoffNavigationSubscription=null;pluginCommands=[];pluginCommandsSubscription=null;async initNewsFeed(){let R=async(a)=>{return xi(a,void 0,this.widget.dependencies.configService)},T=RB0();this.newsFeedReader=new vJR(T,R,"/news.rss"),this.ne