
// === compaction @1222824 ===
n;return this.attachedPool.getTransportConnectionState()}getTransportConnectionRole(){if(!this.attachedPool?.getTransportConnectionRole)return;return this.attachedPool.getTransportConnectionRole()}getCompactionStatus(){if(!this.attachedPool?.getCompactionStatus)return;return this.attachedPool.getCompactionStatus()}attach(R){if(this.attached)throw Error("DeferredThreadPool is already attached");this.attached=!0,this.attachedPool=R;let T=null,a=null;this.attachedPoolSubscriptions=[R.recentThreadIDs$.subscribe((e)=>this.recentThreadIDsSubject.next(e)),R.threadTitles$.subscribe((e)=>this.threadTitlesSubject.next(e)),R.allConnectedThreadActivityStatuses$.subscribe((e)=>this.allConnectedThreadActi

// === compaction @1222824 ===
n;return this.attachedPool.getTransportConnectionState()}getTransportConnectionRole(){if(!this.attachedPool?.getTransportConnectionRole)return;return this.attachedPool.getTransportConnectionRole()}getCompactionStatus(){if(!this.attachedPool?.getCompactionStatus)return;return this.attachedPool.getCompactionStatus()}attach(R){if(this.attached)throw Error("DeferredThreadPool is already attached");this.attached=!0,this.attachedPool=R;let T=null,a=null;this.attachedPoolSubscriptions=[R.recentThreadIDs$.subscribe((e)=>this.recentThreadIDsSubject.next(e)),R.threadTitles$.subscribe((e)=>this.threadTitlesSubject.next(e)),R.allConnectedThreadActivityStatuses$.subscribe((e)=>this.allConnectedThreadActi

// === thinking/reasoning @4673009 ===
l(),pluginName:u3}),sKR=X.strictObject({"agent.deepReasoningEffort":X.enum(["medium","high","xhigh"]).optional(),"agent.skipTitleGenerationIfMessageContains":X.array(X.string()).optional(),"anthropic.thinking.enabled":X.boolean().optional(),"anthropic.interleavedThinking.enabled":X.boolean().optional(),"anthropic.temperature":X.number().optional(),"anthropic.effort":X.enum(["low","medium","high","max"]).optional(),"anthropic.speed":X.enum(["standard","fast"]).optional(),"anthropic.provider":X.enum(["anthropic","vertex"]).optional(),"openai.speed":X.enum(["standard","fast"]).optional(),"internal.compactionThresholdPercent":X.number().min(0).max(100).optional(),"internal.model":X.union([X.stri

// === thinking/reasoning @4545657 ===
iting for preventSleep to clear after shutdown starts. Default: ${IR0}. If sleepGracePeriod is unset, custom legacy onSleepTimeout and waitUntilTimeout values still factor into the effective shutdown budget.`),onSleepTimeout:X.number().optional().describe(`Deprecated. Legacy timeout in ms for onSleep when sleepGracePeriod is not set. Must be less than ACTOR_STOP_THRESHOLD_MS. Default: ${OzR}`),onDestroyTimeout:X.number().optional().describe("Timeout in ms for onDestroy handler. Default: 5000"),stateSaveInterval:X.number().optional().describe("Interval in ms between automatic state saves. Default: 1000"),actionTimeout:X.number().optional().describe("Timeout in ms for action handlers. Default:

// === provider xai @2793649 ===
t()});Vm=SR(()=>{Fr()});ze=SR(()=>{v9={ANTHROPIC:"anthropic",BASENTEN:"baseten",OPENAI:"openai",XAI:"xai",CEREBRAS:"cerebras",FIREWORKS:"fireworks",GROQ:"groq",MOONSHOT:"moonshotai",OPENROUTER:"openrouter",VERTEXAI:"vertexai"},n8={CLAUDE_SONNET_4:{provider:v9.ANTHROPIC,name:"claude-sonnet-4-20250514",displayName:"Claude Sonnet 4",contextWindow:1e6,maxOutputTokens:32000,pricing:{input:3,output:15,cached:0.3,cacheWrite:3.75,cacheTTL:300},capabilities:{reasoning:!0,vision:!0,tools:!0}},CLAUDE_SONNE

// === provider cerebras @2793664 ===
>{Fr()});ze=SR(()=>{v9={ANTHROPIC:"anthropic",BASENTEN:"baseten",OPENAI:"openai",XAI:"xai",CEREBRAS:"cerebras",FIREWORKS:"fireworks",GROQ:"groq",MOONSHOT:"moonshotai",OPENROUTER:"openrouter",VERTEXAI:"vertexai"},n8={CLAUDE_SONNET_4:{provider:v9.ANTHROPIC,name:"claude-sonnet-4-20250514",displayName:"Claude Sonnet 4",contextWindow:1e6,maxOutputTokens:32000,pricing:{input:3,output:15,cached:0.3,cacheWrite:3.75,cacheTTL:300},capabilities:{reasoning:!0,vision:!0,tools:!0}},CLAUDE_SONNET_4_5:{provider

// === provider fireworks @2793685 ===
9={ANTHROPIC:"anthropic",BASENTEN:"baseten",OPENAI:"openai",XAI:"xai",CEREBRAS:"cerebras",FIREWORKS:"fireworks",GROQ:"groq",MOONSHOT:"moonshotai",OPENROUTER:"openrouter",VERTEXAI:"vertexai"},n8={CLAUDE_SONNET_4:{provider:v9.ANTHROPIC,name:"claude-sonnet-4-20250514",displayName:"Claude Sonnet 4",contextWindow:1e6,maxOutputTokens:32000,pricing:{input:3,output:15,cached:0.3,cacheWrite:3.75,cacheTTL:300},capabilities:{reasoning:!0,vision:!0,tools:!0}},CLAUDE_SONNET_4_5:{provider:v9.ANTHROPIC,name:"c

// === provider groq @2793702 ===
hropic",BASENTEN:"baseten",OPENAI:"openai",XAI:"xai",CEREBRAS:"cerebras",FIREWORKS:"fireworks",GROQ:"groq",MOONSHOT:"moonshotai",OPENROUTER:"openrouter",VERTEXAI:"vertexai"},n8={CLAUDE_SONNET_4:{provider:v9.ANTHROPIC,name:"claude-sonnet-4-20250514",displayName:"Claude Sonnet 4",contextWindow:1e6,maxOutputTokens:32000,pricing:{input:3,output:15,cached:0.3,cacheWrite:3.75,cacheTTL:300},capabilities:{reasoning:!0,vision:!0,tools:!0}},CLAUDE_SONNET_4_5:{provider:v9.ANTHROPIC,name:"claude-sonnet-4-5-

// === provider openrouter @2793742 ===
i",XAI:"xai",CEREBRAS:"cerebras",FIREWORKS:"fireworks",GROQ:"groq",MOONSHOT:"moonshotai",OPENROUTER:"openrouter",VERTEXAI:"vertexai"},n8={CLAUDE_SONNET_4:{provider:v9.ANTHROPIC,name:"claude-sonnet-4-20250514",displayName:"Claude Sonnet 4",contextWindow:1e6,maxOutputTokens:32000,pricing:{input:3,output:15,cached:0.3,cacheWrite:3.75,cacheTTL:300},capabilities:{reasoning:!0,vision:!0,tools:!0}},CLAUDE_SONNET_4_5:{provider:v9.ANTHROPIC,name:"claude-sonnet-4-5-20250929",displayName:"Claude Sonnet 4.5

// === provider vertex @4673325 ===
),"anthropic.speed":X.enum(["standard","fast"]).optional(),"anthropic.provider":X.enum(["anthropic","vertex"]).optional(),"openai.speed":X.enum(["standard","fast"]).optional(),"internal.compactionThresholdPercent":X.number().min(0).max(100).optional(),"internal.model":X.union([X.string(),X.record(X.string(),X.string())]).optional(),"internal.oracleReasoningEffort":X.enum(["none","minimal","low","medium","high","xhigh"]).optional(),"gemini.thinkingLevel":X.enum(["minimal","low","medium","high"]).

// === provider baseten @2793619 ===
ral(["T-",XtR])});Fr=SR(()=>{vt()});Vm=SR(()=>{Fr()});ze=SR(()=>{v9={ANTHROPIC:"anthropic",BASENTEN:"baseten",OPENAI:"openai",XAI:"xai",CEREBRAS:"cerebras",FIREWORKS:"fireworks",GROQ:"groq",MOONSHOT:"moonshotai",OPENROUTER:"openrouter",VERTEXAI:"vertexai"},n8={CLAUDE_SONNET_4:{provider:v9.ANTHROPIC,name:"claude-sonnet-4-20250514",displayName:"Claude Sonnet 4",contextWindow:1e6,maxOutputTokens:32000,pricing:{input:3,output:15,cached:0.3,cacheWrite:3.75,cacheTTL:300},capabilities:{reasoning:!0,vis

// === agentMode @896733 ===
return"gpt";if(T==="xai")return"xai";if(T==="vertexai")return"gemini";return"default"}function vDT({agentMode:R,model:T,provider:a}){if(R===u0R)return"aggman";if(Wr(R))return"free";if(R==="rush")return"rush";if(R==="deep")return"deep";if(CPR(R))return"internal";let e=fn(`${a}/${T}`);if(e)return $DT(e);return jDT(T,a)}async function vf(R,T,{enableTaskList:a,enableTask:e,enableOracle:r,enableDiagnostics:h,enableChart:t=!0},{model:i,provider:c,agentMode:o},C){if(sDT(R.serverStatus))a=!0;let g=Boolean(T.mainThreadID),l=await y0(g?R.toolService.getToolsForMode(o,g):R.toolService.getTools(o),C),n=aw

// === agentMode @466567 ===
{return value===(value|0)}function isUint32(value){return value===value>>>0}var octalReg=/^[0-7]+$/,modeDesc="must be a 32-bit unsigned integer or an octal string";function parseFileMode(value,name,def){if(typeof value>"u")value=def;if(typeof value==="string"){if(RegExpPrototypeExec(octalReg,value)===null)throw new ERR_INVALID_ARG_VALUE(name,value,modeDesc);value=NumberParseInt(value,8)}return validateUint32(value,name),value}var validateInteger=hideStackFrames((value,name,min=NumberMIN_SAFE_INTEGER,max=NumberMAX_SAFE_INTEGER)=>{if(typeof value!=="number")throw new ERR_INVALID_ARG_TYPE(name,"n

// === image paste @4829982 ===
dleBracketedPaste(R){if(R.final==="~"&&R.params.length===1){let T=R.params[0]?.value;if(T===200)return this.inPaste=!0,this.pasteBuffer="",!0;else if(T===201){if(this.inPaste)this.inPaste=!1,this.emitPasteEvent({type:"paste",text:this.pasteBuffer}),this.pasteBuffer="";return!0}}return!1}emitPasteEvent(R){for(let T of this.pasteHandlers)T(R)}};hT();UxR=a9+"0m",Hy0=a9+"m",Wy0=a9+"H",qy0=a9+"?25l",Gy0=a9+"?25h",zy0=a9+"2J",Ky0=a9+"?2026h",Vy0=a9+"?2026l",Fy0=a9+"?2004h",Xy0=a9+"?2004l",WxR=[...Array.from({length:216},(R,T)=>{let a=Math.floor(T/36),e=Math.floor(T%36/6),r=T%6,h=(t)=>t===0?0:55+t*40;return[h(a),h(e),h(r)]}),...Array.from({length:24},(R,T)=>{let a=8+T*10;return[a,a,a]})],qxR=new Map;Yy0=a9+"?1049h",Qy0=a9+"?1049l",Zy0=a9+"?1002h"+a9+"?1003h"+a9+"?1004h"+a9+"?1006h",Jy0=a9+"?1002l

// === image paste @4711812 ===
,53,117]),YF0=Buffer.from([27,91,50,55,59,50,59,49,51,126]),QF0=Buffer.from([27,91,50,55,59,53,59,49,51,126]),ZF0=Buffer.from([27,91,50,55,59,56,59,49,51,126]),Zl0={ESC:Buffer.from([27,91,50,55,117]),CTRL_A:Buffer.from([27,91,57,55,59,53,117]),CTRL_B:Buffer.from([27,91,57,56,59,53,117]),CTRL_C:Buffer.from([27,91,57,57,59,53,117]),CTRL_D:Buffer.from([27,91,49,48,48,59,53,117]),CTRL_E:Buffer.from([27,91,49,48,49,59,53,117]),CTRL_F:Buffer.from([27,91,49,48,50,59,53,117]),CTRL_H:Buffer.from([27,91,49,48,52,59,53,117]),CTRL_K:Buffer.from([27,91,49,48,55,59,53,117]),CTRL_L:Buffer.from([27,91,49,48,56,59,53,117]),CTRL_N:Buffer.from([27,91,49,49,48,59,53,117]),CTRL_P:Buffer.from([27,91,49,49,50,59,53,117]),CTRL_U:Buffer.from([27,91,49,49,55,59,53,117]),CTRL_W:Buffer.from([27,91,49,49,57,59,53,117]

// === image paste @1859836 ===
s.Forms.Clipboard]::ContainsImage()) { exit 2 }; $image = [System.Windows.Forms.Clipboard]::GetImage(); if ($null -eq $image) { exit 3 }; $tempFile = Join-Path ([System.IO.Path]::GetTempPath()) ("amp-paste-{0}.png" -f [System.Guid]::NewGuid().ToString("N")); $image.Save($tempFile, [System.Drawing.Imaging.ImageFormat]::Png); Write-Output $tempFile',hW,ShR="normal",Qx="hidden",BJR,UJR,HJR,WJR,qJR,GJR,LB0=1500,DB0=200,zJR,KJR,BB0=200,VJR,FJR,qB0=23,xhR,YJR,QJR,ZJR,JJR,RRT,IhR,TRT,aRT,KB0=10,VB0=35,FB0=2,Ta=8,$sR=2,XB0=1,eRT=20,de,qz,QB0,rRT=10240,JB0=8,phR,hRT,KS,oRT,kQ=3,C60=0.25,A60=0.15,lRT,nRT,Ny,CRT,ART,XL,yRT,bRT,uRT,dRT,kRT,SQ,SRT,IRT,pRT="c446b2e9b16cdc06df2ec285894d6421",$60="5ea19563777f4ade8707fc56f7e7a388",j60="amp-thread-worker",v60,$RT,jRT,zl,vRT,vhR,mRT,ORT="\u2588",PRT="\u2588

// === toast/notification @5182062 ===
s.features:this.tuiContext.features,showStatusMessage:(t,i=2000)=>{this.showStatusMessage(t,i)},showToast:(t,i="success",c)=>{this.toastController.show(t,i,c)},getThemeName:()=>W40(e).themeName,isMessageViewInteractionActive:this.isMessageViewInSelectionMode||this.messageViewController.editingMessageOrdinal!==null,enterHandoffMode:this.enterHandoffMode,isInHandoffMode:this.handoffState.isInHandoffMode,enterQueueMode:this.enterQueueMode,submitQueue:this.submitQueue,isInQueueMode:this.isInQueueMod