
// === editMessage @5162709 ===
e(()=>{this.onThreadSwitch(),this.previousThreadIdForHint=R??null})};canChangeAgentModeInPromptEditor(){let R=!this.widget.dependencies.activeThreadHandle.isThreadEmpty(),T=this.messageViewController.editingMessageOrdinal===0,{isInHandoffMode:a,isGeneratingHandoff:e}=this.handoffState;return!R||T||a&&!e}getProspectiveAgentMode(){return this.prospectiveAgentMode}setProspectiveAgentMode(R){let T=this.agentModeController.clampToVisibleMode(R);if(this.prospectiveAgentMode===T)return;this.prospectiveAgentMode=T,this.setState(()=>{})}getEffectiveAgentMode(){return(this.canChangeAgentModeInPromptEditor()?this.getProspectiveAgentMode():null)??this.agentModeController.getEffectiveMode()}isProcessing(){let{activeThreadHandle:R,threadState:T}=this.widget.dependencies;if(!R.getThreadID())return!1;if(T

// === editMessage @5182249 ===
ge(t,i)},showToast:(t,i="success",c)=>{this.toastController.show(t,i,c)},getThemeName:()=>W40(e).themeName,isMessageViewInteractionActive:this.isMessageViewInSelectionMode||this.messageViewController.editingMessageOrdinal!==null,enterHandoffMode:this.enterHandoffMode,isInHandoffMode:this.handoffState.isInHandoffMode,enterQueueMode:this.enterQueueMode,submitQueue:this.submitQueue,isInQueueMode:this.isInQueueMode,addPendingSkill:(t)=>{this.widget.dependencies.activeThreadHandle.addPendingSkill(t)},onThreadMentionSelected:this.paletteOnThreadMentionSelected??void 0,canChangeAgentModeInPromptEditor:()=>this.canChangeAgentModeInPromptEditor(),pluginCommands:this.pluginCommands,executePluginCommand:this.widget.dependencies.pluginService?(t,i,c)=>this.widget.dependencies.pluginService.commands.ex

// === editMessage @5187224 ===
oggleMode(T,R);if(a)this.prospectiveAgentMode=a,this.setState(()=>{this.showImageUnsupportedHint=!1,this.agentModePulseSeq++})};handleMessageViewControllerUpdate=()=>{let R=this.messageViewController.editingMessageOrdinal;if(R===this.lastEditingMessageOrdinal)return;if(this.lastEditingMessageOrdinal!==null&&R===null)this.prospectiveAgentMode=null;this.lastEditingMessageOrdinal=R,this.setState(()=>{})};showStatusMessage(R,T=2000){if(this.statusMessageTimer)clearTimeout(this.statusMessageTimer);this.setState(()=>{this.statusMessage=R}),this.statusMessageTimer=setTimeout(()=>{this.setState(()=>{this.statusMessage=null}),this.statusMessageTimer=null},T)}applyDeepReasoningEffort(R){this.deepReasoningEffort=R,Lo("agent.deepReasoningEffort",R)}commitDeepReasoningEffort(R){let T=this.deepReasoning

// === context @2793881 ===
LAUDE_SONNET_4:{provider:v9.ANTHROPIC,name:"claude-sonnet-4-20250514",displayName:"Claude Sonnet 4",contextWindow:1e6,maxOutputTokens:32000,pricing:{input:3,output:15,cached:0.3,cacheWrite:3.75,cacheTTL:300},capabilities:{reasoning:!0,vision:!0,tools:!0}},CLAUDE_SONNET_4_5:{provider:v9.ANTHROPIC,name:"claude-sonnet-4-5-20250929",displayName:"Claude Sonnet 4.5",contextWindow:1e6,maxOutputTokens:32000,pricing:{input:3,output:15,cached:0.3,cacheWrite:3.75,cacheTTL:300},capabilities:{reasoning:!0,vi

// === context @2794144 ===
SONNET_4_5:{provider:v9.ANTHROPIC,name:"claude-sonnet-4-5-20250929",displayName:"Claude Sonnet 4.5",contextWindow:1e6,maxOutputTokens:32000,pricing:{input:3,output:15,cached:0.3,cacheWrite:3.75,cacheTTL:300},capabilities:{reasoning:!0,vision:!0,tools:!0}},CLAUDE_SONNET_4_6:{provider:v9.ANTHROPIC,name:"claude-sonnet-4-6",displayName:"Claude Sonnet 4.6",contextWindow:1e6,maxOutputTokens:64000,pricing:{input:3,output:15,cached:0.3,cacheWrite:3.75,cacheTTL:300},capabilities:{reasoning:!0,vision:!0,t

// === context @2794398 ===
},CLAUDE_SONNET_4_6:{provider:v9.ANTHROPIC,name:"claude-sonnet-4-6",displayName:"Claude Sonnet 4.6",contextWindow:1e6,maxOutputTokens:64000,pricing:{input:3,output:15,cached:0.3,cacheWrite:3.75,cacheTTL:300},capabilities:{reasoning:!0,vision:!0,tools:!0}},CLAUDE_OPUS_4:{provider:v9.ANTHROPIC,name:"claude-opus-4-20250514",displayName:"Claude Opus 4",contextWindow:200000,maxOutputTokens:32000,pricing:{input:15,output:75,cached:1.5,cacheWrite:18.75,cacheTTL:300},capabilities:{reasoning:!0,vision:!0

// === context @2794649 ===
!0}},CLAUDE_OPUS_4:{provider:v9.ANTHROPIC,name:"claude-opus-4-20250514",displayName:"Claude Opus 4",contextWindow:200000,maxOutputTokens:32000,pricing:{input:15,output:75,cached:1.5,cacheWrite:18.75,cacheTTL:300},capabilities:{reasoning:!0,vision:!0,tools:!0}},CLAUDE_OPUS_4_1:{provider:v9.ANTHROPIC,name:"claude-opus-4-1-20250805",displayName:"Claude Opus 4.1",contextWindow:200000,maxOutputTokens:32000,pricing:{input:15,output:75,cached:1.5,cacheWrite:18.75,cacheTTL:300},capabilities:{reasoning:!

// === context @2794911 ===
LAUDE_OPUS_4_1:{provider:v9.ANTHROPIC,name:"claude-opus-4-1-20250805",displayName:"Claude Opus 4.1",contextWindow:200000,maxOutputTokens:32000,pricing:{input:15,output:75,cached:1.5,cacheWrite:18.75,cacheTTL:300},capabilities:{reasoning:!0,vision:!0,tools:!0}},CLAUDE_OPUS_4_5:{provider:v9.ANTHROPIC,name:"claude-opus-4-5-20251101",displayName:"Claude Opus 4.5",contextWindow:200000,maxOutputTokens:32000,pricing:{input:5,output:25,cached:0.5,cacheWrite:6.25,cacheTTL:300},capabilities:{reasoning:!0,

// === context @2795173 ===
LAUDE_OPUS_4_5:{provider:v9.ANTHROPIC,name:"claude-opus-4-5-20251101",displayName:"Claude Opus 4.5",contextWindow:200000,maxOutputTokens:32000,pricing:{input:5,output:25,cached:0.5,cacheWrite:6.25,cacheTTL:300},capabilities:{reasoning:!0,vision:!0,tools:!0}},CLAUDE_OPUS_4_6:{provider:v9.ANTHROPIC,name:"claude-opus-4-6",displayName:"Claude Opus 4.6",contextWindow:332000,maxOutputTokens:32000,pricing:{input:5,output:25,cached:0.5,cacheWrite:6.25,cacheTTL:300},capabilities:{reasoning:!0,vision:!0,t

// === context @2795424 ===
ls:!0}},CLAUDE_OPUS_4_6:{provider:v9.ANTHROPIC,name:"claude-opus-4-6",displayName:"Claude Opus 4.6",contextWindow:332000,maxOutputTokens:32000,pricing:{input:5,output:25,cached:0.5,cacheWrite:6.25,cacheTTL:300},capabilities:{reasoning:!0,vision:!0,tools:!0}},CLAUDE_HAIKU_4_5:{provider:v9.ANTHROPIC,name:"claude-haiku-4-5-20251001",displayName:"Claude Haiku 4.5",contextWindow:200000,maxOutputTokens:64000,pricing:{input:1,output:5,cached:0.1,cacheWrite:1.25,cacheTTL:300},capabilities:{reasoning:!0,

// === context @2795687 ===
DE_HAIKU_4_5:{provider:v9.ANTHROPIC,name:"claude-haiku-4-5-20251001",displayName:"Claude Haiku 4.5",contextWindow:200000,maxOutputTokens:64000,pricing:{input:1,output:5,cached:0.1,cacheWrite:1.25,cacheTTL:300},capabilities:{reasoning:!0,vision:!0,tools:!0}},GPT_5:{provider:v9.OPENAI,name:"gpt-5",displayName:"GPT-5",contextWindow:400000,maxOutputTokens:128000,pricing:{input:1.25,output:10,cached:0.125},capabilities:{reasoning:!0,vision:!0,tools:!0}},GPT_5_1:{provider:v9.OPENAI,name:"gpt-5.1",disp

// === context @2795904 ===
ities:{reasoning:!0,vision:!0,tools:!0}},GPT_5:{provider:v9.OPENAI,name:"gpt-5",displayName:"GPT-5",contextWindow:400000,maxOutputTokens:128000,pricing:{input:1.25,output:10,cached:0.125},capabilities:{reasoning:!0,vision:!0,tools:!0}},GPT_5_1:{provider:v9.OPENAI,name:"gpt-5.1",displayName:"GPT-5.1",contextWindow:400000,maxOutputTokens:128000,pricing:{input:1.25,output:10,cached:0.125},capabilities:{reasoning:!0,vision:!0,tools:!0}},GPT_5_2:{provider:v9.OPENAI,name:"gpt-5.2",displayName:"GPT-5.2

// === context @2796105 ===
{reasoning:!0,vision:!0,tools:!0}},GPT_5_1:{provider:v9.OPENAI,name:"gpt-5.1",displayName:"GPT-5.1",contextWindow:400000,maxOutputTokens:128000,pricing:{input:1.25,output:10,cached:0.125},capabilities:{reasoning:!0,vision:!0,tools:!0}},GPT_5_2:{provider:v9.OPENAI,name:"gpt-5.2",displayName:"GPT-5.2",contextWindow:400000,maxOutputTokens:128000,pricing:{input:1.75,output:14,cached:0.175},capabilities:{reasoning:!0,vision:!0,tools:!0}},GPT_5_4:{provider:v9.OPENAI,name:"gpt-5.4",displayName:"GPT-5.4

// === context @2796306 ===
{reasoning:!0,vision:!0,tools:!0}},GPT_5_2:{provider:v9.OPENAI,name:"gpt-5.2",displayName:"GPT-5.2",contextWindow:400000,maxOutputTokens:128000,pricing:{input:1.75,output:14,cached:0.175},capabilities:{reasoning:!0,vision:!0,tools:!0}},GPT_5_4:{provider:v9.OPENAI,name:"gpt-5.4",displayName:"GPT-5.4",contextWindow:400000,maxOutputTokens:128000,pricing:{input:2.5,output:15,cached:0.25},capabilities:{reasoning:!0,vision:!0,tools:!0}},GPT_5_CODEX:{provider:v9.OPENAI,name:"gpt-5-codex",displayName:"G

// === context @2796507 ===
{reasoning:!0,vision:!0,tools:!0}},GPT_5_4:{provider:v9.OPENAI,name:"gpt-5.4",displayName:"GPT-5.4",contextWindow:400000,maxOutputTokens:128000,pricing:{input:2.5,output:15,cached:0.25},capabilities:{reasoning:!0,vision:!0,tools:!0}},GPT_5_CODEX:{provider:v9.OPENAI,name:"gpt-5-codex",displayName:"GPT-5 Codex",contextWindow:400000,maxOutputTokens:128000,pricing:{input:1.25,output:10,cached:0.125},capabilities:{reasoning:!0,tools:!0}},GPT_5_1_CODEX:{provider:v9.OPENAI,name:"gpt-5.1-codex",displayN

// === context @2796718 ===
0,vision:!0,tools:!0}},GPT_5_CODEX:{provider:v9.OPENAI,name:"gpt-5-codex",displayName:"GPT-5 Codex",contextWindow:400000,maxOutputTokens:128000,pricing:{input:1.25,output:10,cached:0.125},capabilities:{reasoning:!0,tools:!0}},GPT_5_1_CODEX:{provider:v9.OPENAI,name:"gpt-5.1-codex",displayName:"GPT-5.1 Codex",contextWindow:400000,maxOutputTokens:128000,pricing:{input:1.25,output:10,cached:0.125},capabilities:{reasoning:!0,tools:!0}},GPT_5_2_CODEX:{provider:v9.OPENAI,name:"gpt-5.2-codex",displayNam

// === fileChanges @920934 ===
 j0(void 0);ephemeralErrorRetryAttempt=0;retryCountdownSeconds=new j0(void 0);retryTimer=null;retrySession=0;_inferenceState=new j0("idle");_turnStartTime=new j0(void 0);_turnElapsedMs=new j0(void 0);fileChanges=new j0({files:[]});get inferenceState(){return this._inferenceState.getValue()}toolCallUpdates=new H0;trackedFiles=new Mo;discoveredGuidanceFileURIs=new Set;fs;cachedFileChanges=[];disposed$=new H0;isDisposed=!1;shouldContinueAfterRejection=!1;_pendingSkills=new j0([]);handoffState=new j0(void 0);pendingSkills=this._pendingSkills.pipe(f9(),k3({shouldCountRefs:!0}));_awaitingSkillInvocation=new j0([]);toolOrchestrator;currentAgentSpan=null;currentSpan=null;traceStore;constructor(R,T){this.deps=R,this.threadID=T,this.fs=E3R({fileChangeTrackerStorage:this.deps.fileChangeTrackerStorage

// === fileChanges @923947 ===
s=[];if(!a.activatedSkills.some((e)=>e.name===T.name))a.activatedSkills.push({name:T.name,arguments:T.arguments})})}status=this.state.pipe(P9((R)=>R==="active"?p3(this._inferenceState.pipe(f9()),this.fileChanges.pipe(f9()),this.ephemeralError,this.handoffState.pipe(f9()),this.retryCountdownSeconds.pipe(f9()),this._turnStartTime.pipe(f9()),this._turnElapsedMs.pipe(f9()),this.toolCallUpdates.pipe(V3(void 0))).pipe(JT(([T,a,e,r,h,t,i])=>({state:R,inferenceState:T,fileChanges:a,ephemeralError:e?{message:e.message,stack:"stack"in e?e.stack:void 0,error:"error"in e&&e.error&&typeof e.error==="object"&&"error"in e.error?e.error.error:void 0,retryCountdownSeconds:h}:void 0,handoff:r,turnStartTime:t,turnElapsedMs:i})),v$(this.disposed$)):CT.of({state:R})),k3({shouldCountRefs:!0}));threadReadWriter=

// === fileChanges @924212 ===
(f9()),this.retryCountdownSeconds.pipe(f9()),this._turnStartTime.pipe(f9()),this._turnElapsedMs.pipe(f9()),this.toolCallUpdates.pipe(V3(void 0))).pipe(JT(([T,a,e,r,h,t,i])=>({state:R,inferenceState:T,fileChanges:a,ephemeralError:e?{message:e.message,stack:"stack"in e?e.stack:void 0,error:"error"in e&&e.error&&typeof e.error==="object"&&"error"in e.error?e.error.error:void 0,retryCountdownSeconds:h}:void 0,handoff:r,turnStartTime:t,turnElapsedMs:i})),v$(this.disposed$)):CT.of({state:R})),k3({shouldCountRefs:!0}));threadReadWriter=null;get thread(){if(!this.threadReadWriter)throw Error(`thread read-writer not initialized for ThreadWorker: ${this.threadID}`);return this.threadReadWriter.read()}set thread(R){if(!this.threadReadWriter)throw Error(`thread read-writer not initialized for ThreadWo

// === fileChanges @950864 ===
Enabled())await this.cleanupFileChanges();await this.cleanupForkThreads()}async updateFileChanges(){if(await this.isAutoSnapshotEnabled())return;this.cachedFileChanges=await B7R(this.fs.tracker),this.fileChanges.next({files:this.cachedFileChanges})}async injectPendingSkills(R,T){let a=R.map((e)=>e.name);Z.info("Adding info message to prompt skill invocation",{threadID:this.threadID,skillNames:a}),this._awaitingSkillInvocation.next(R),this.thread=Dr(this.thread,(e)=>{let r=e.nextMessageId??0;e.nextMessageId=r+1,e.messages.push({role:"info",messageId:r,content:[{type:"text",text:`You MUST call the ${lc} tool to load: ${a.join(", ")}. Do this immediately before responding.`}]}),e.v++})}checkAndAppendAwaitedSkills(){let R=this._awaitingSkillInvocation.getValue();if(R.length===0)return;this._aw

// === fileChanges @953450 ===
ator.cancelAll("system:disposed"),this.disposed$.next(),this.disposed$.complete(),this.clearRetryCountdown(),this._state.complete(),this.ephemeralError.complete(),this._inferenceState.complete(),this.fileChanges.complete(),this.toolCallUpdates.complete(),this.retryCountdownSeconds.complete(),this.toolOrchestrator.dispose(),this.ops.inference)this.ops.inference.abort(),this.ops.inference=null;if(this.ops.titleGeneration)this.ops.titleGeneration.abort(),this.ops.titleGeneration=null;if(this.fs.tracker.dispose(),this.threadReadWriter)await this.threadReadWriter.asyncDispose(),this.threadReadWriter=null}async getSelectedAgentMode(){let R=await this.getConfig(),{agentMode:T}=Cn(R.settings,this.thread);return T}}function YDT(R,T,a=!1){let e=Er(R,"assistant");if(!e||e.state.type!=="complete"||e.s

// === fileChanges @1220083 ===
olve=null;readyReject=null;constructor(R=jt()){this.placeholderThreadID=R;let T=new j0(jM0(this.placeholderThreadID)),a=new j0(new Map),e=new j0(t3R(T.getValue(),{state:"active",inferenceState:"idle",fileChanges:{files:[]}}));this.threadHandlesSubject=new j0(ZrR({thread$:T,threadViewState$:e,toolProgressByToolUseID$:a,pendingApprovals$:this.pendingApprovalsSubject,pendingSkills$:this.pendingSkillsSubject,getCurrentThread:()=>T.getValue(),sendMessage:async(r)=>(await this.waitForActiveHandle()).sendMessage(r),restoreTo:async(r)=>(await this.waitForActiveHandle()).restoreTo(r),queueMessage:async(r)=>(await this.waitForActiveHandle()).queueMessage(r),discardQueuedMessages:async()=>(await this.waitForActiveHandle()).discardQueuedMessages(),setTitle:async(r)=>(await this.waitForActiveHandle()).

// === fileChanges @1226410 ===
{let T=mM0(R);if(T)return T;return!1}function oB(R,T,a={files:[]},e=void 0){let r=vM0(R),h=T==="awaiting_approval"?1:0;if(T==="working"||T==="streaming")return{state:"active",inferenceState:"running",fileChanges:a,ephemeralError:e,interactionState:!1,toolState:{running:0,blocked:0}};if(T==="tool_use"||T==="running_tools"){let t=r.running;return{state:"active",inferenceState:"idle",fileChanges:a,ephemeralError:e,interactionState:t>0?"tool-running":!1,toolState:{running:t,blocked:h}}}if(T==="awaiting_approval")return{state:"active",inferenceState:"idle",fileChanges:a,ephemeralError:e,interactionState:"user-tool-approval",toolState:{running:r.running,blocked:h}};return{state:"active",inferenceState:"idle",fileChanges:a,ephemeralError:e,interactionState:fM0(R),toolState:{running:r.running,bloc

// === fileChanges @1226594 ===
State:"running",fileChanges:a,ephemeralError:e,interactionState:!1,toolState:{running:0,blocked:0}};if(T==="tool_use"||T==="running_tools"){let t=r.running;return{state:"active",inferenceState:"idle",fileChanges:a,ephemeralError:e,interactionState:t>0?"tool-running":!1,toolState:{running:t,blocked:h}}}if(T==="awaiting_approval")return{state:"active",inferenceState:"idle",fileChanges:a,ephemeralError:e,interactionState:"user-tool-approval",toolState:{running:r.running,blocked:h}};return{state:"active",inferenceState:"idle",fileChanges:a,ephemeralError:e,interactionState:fM0(R),toolState:{running:r.running,blocked:h}}}class CZR{authoritativeThread;currentAgentLoopState;pendingMessageSubmits=[];pendingQueuedSubmits=[];pendingQueuedInterruptMessageIDs=new Set;pendingEdit;constructor(R,T){this.

// === fileChanges @1226768 ===
ve",inferenceState:"idle",fileChanges:a,ephemeralError:e,interactionState:t>0?"tool-running":!1,toolState:{running:t,blocked:h}}}if(T==="awaiting_approval")return{state:"active",inferenceState:"idle",fileChanges:a,ephemeralError:e,interactionState:"user-tool-approval",toolState:{running:r.running,blocked:h}};return{state:"active",inferenceState:"idle",fileChanges:a,ephemeralError:e,interactionState:fM0(R),toolState:{running:r.running,blocked:h}}}class CZR{authoritativeThread;currentAgentLoopState;pendingMessageSubmits=[];pendingQueuedSubmits=[];pendingQueuedInterruptMessageIDs=new Set;pendingEdit;constructor(R,T){this.authoritativeThread=R,this.currentAgentLoopState=T}setAgentLoopState(R){this.currentAgentLoopState=R}optimisticUpdate(R){switch(R.type){case"submit":return this.optimisticSub

// === fileChanges @1226922 ===
")return{state:"active",inferenceState:"idle",fileChanges:a,ephemeralError:e,interactionState:"user-tool-approval",toolState:{running:r.running,blocked:h}};return{state:"active",inferenceState:"idle",fileChanges:a,ephemeralError:e,interactionState:fM0(R),toolState:{running:r.running,blocked:h}}}class CZR{authoritativeThread;currentAgentLoopState;pendingMessageSubmits=[];pendingQueuedSubmits=[];pendingQueuedInterruptMessageIDs=new Set;pendingEdit;constructor(R,T){this.authoritativeThread=R,this.currentAgentLoopState=T}setAgentLoopState(R){this.currentAgentLoopState=R}optimisticUpdate(R){switch(R.type){case"submit":return this.optimisticSubmit(R);case"discard-queued":return this.pendingQueuedSubmits=[],this.pendingQueuedInterruptMessageIDs.clear(),this.buildProjection();case"interrupt-queued

// === retry countdown @920775 ===
es:{},inference:null,titleGeneration:null};_state=new j0("initial");state=this._state.pipe(f9(),k3({shouldCountRefs:!0}));handleMutex=new fu;ephemeralError=new j0(void 0);ephemeralErrorRetryAttempt=0;retryCountdownSeconds=new j0(void 0);retryTimer=null;retrySession=0;_inferenceState=new j0("idle");_turnStartTime=new j0(void 0);_turnElapsedMs=new j0(void 0);fileChanges=new j0({files:[]});get inferenceState(){return this._inferenceState.getValue()}toolCallUpdates=new H0;trackedFiles=new Mo;discoveredGuidanceFileURIs=new Set;fs;cachedFileChanges=[];disposed$=new H0;isDisposed=!1;shouldContinueAfterRejection=!1;_pendingSkills=new j0([]);handoffState=new j0(void 0);pendingSkills=this._pendingSkills.pipe(f9(),k3({shouldCountRefs:!0}));_awaitingSkillInvocation=new j0([]);toolOrchestrator;currentA

// === retry countdown @920775 ===
es:{},inference:null,titleGeneration:null};_state=new j0("initial");state=this._state.pipe(f9(),k3({shouldCountRefs:!0}));handleMutex=new fu;ephemeralError=new j0(void 0);ephemeralErrorRetryAttempt=0;retryCountdownSeconds=new j0(void 0);retryTimer=null;retrySession=0;_inferenceState=new j0("idle");_turnStartTime=new j0(void 0);_turnElapsedMs=new j0(void 0);fileChanges=new j0({files:[]});get inferenceState(){return this._inferenceState.getValue()}toolCallUpdates=new H0;trackedFiles=new Mo;discoveredGuidanceFileURIs=new Set;fs;cachedFileChanges=[];disposed$=new H0;isDisposed=!1;shouldContinueAfterRejection=!1;_pendingSkills=new j0([]);handoffState=new j0(void 0);pendingSkills=this._pendingSkills.pipe(f9(),k3({shouldCountRefs:!0}));_awaitingSkillInvocation=new j0([]);toolOrchestrator;currentA

// === retry countdown @5158460 ===
GridDragStartHeight=null;previousThreadIdForHint=null;handoffController=null;handoffState={isInHandoffMode:!1,isGeneratingHandoff:!1,isConfirmingAbortHandoff:!1,pendingHandoffPrompt:null,spinner:null,countdownSeconds:null};isInQueueMode=!1;pendingMCPServers=[];mcpTrustSubscription=null;pendingOAuthRequest=null;pendingAuthLogin=null;authStatus="pending";authStatusSubscription=null;authModalKeyInterceptorUnsubscribe=null;queuedInterjectKeyInterceptorUnsubscribe=null;isCreatingAuthLoginSession=!1;queuedPromptAfterAuth=null;pendingInputDialog=null;pendingConfirmDialog=null;mcpServers=[];mcpServersSubscription=null;pluginInfos=[];pluginInfosSubscription=null;agentModeController;prospectiveAgentMode=null;freeTierStatus={canUseAmpFree:!1,isDailyGrantEnabled:!1};agentModePulseSeq=0;lastEffectiveAg

// === bottomGrid @5158200 ===
ibe=null;lastEditingMessageOrdinal=null;skillPreview=null;cachedSkillForPreview=null;newsFeedReader=null;newsFeedEntries=[];newsFeedSubscription=null;bottomGridUserHeight=void 0;bottomGridDragStartY=null;bottomGridDragStartHeight=null;previousThreadIdForHint=null;handoffController=null;handoffState={isInHandoffMode:!1,isGeneratingHandoff:!1,isConfirmingAbortHandoff:!1,pendingHandoffPrompt:null,spinner:null,countdownSeconds:null};isInQueueMode=!1;pendingMCPServers=[];mcpTrustSubscription=null;pendingOAuthRequest=null;pendingAuthLogin=null;authStatus="pending";authStatusSubscription=null;authModalKeyInterceptorUnsubscribe=null;queuedInterjectKe

// === bottomGrid @5158200 ===
ibe=null;lastEditingMessageOrdinal=null;skillPreview=null;cachedSkillForPreview=null;newsFeedReader=null;newsFeedEntries=[];newsFeedSubscription=null;bottomGridUserHeight=void 0;bottomGridDragStartY=null;bottomGridDragStartHeight=null;previousThreadIdForHint=null;handoffController=null;handoffState={isInHandoffMode:!1,isGeneratingHandoff:!1,isConfirmingAbortHandoff:!1,pendingHandoffPrompt:null,spinner:null,countdownSeconds:null};isInQueueMode=!1;pendingMCPServers=[];mcpTrustSubscription=null;pendingOAuthRequest=null;pendingAuthLogin=null;authStatus="pending";authStatusSubscription=null;authModalKeyInterceptorUnsubscribe=null;queuedInterjectKe