
// === toast @691845 ===
vnd.tableschema+jsonapplication/vnd.yamaha.hv-scriptapplication/webpush-options+jsonapplication/x-pkcs7-certificatesaudio/vnd.ms-playready.media.pyaimage/vnd.airzip.accelerator.azvmessage/disposition-notificationtext/vnd.sun.j2me.app-descriptorvideo/vnd.ms-playready.media.pyvapplication/at+jwtapplication/dec-dxapplication/mswordapplication/oscoreapplication/pkcs10application/pkcs12application/riscosapplication/ubjsonapplication/ulpfecapplication/widgetapplication/winhlpapplication/x-bdocapplication/x-bzipapplication/x-chatapplication/x-cpioapplication/x-doomapplication/x-gtarapplication/x-gzipapplication/x-perlapplication/x-sharapplication/x-tadsapplication/x-tgifapplication/x-xfigapplication/xv+xmlaudio/dsr-es201108audio/dsr-es202050audio/dsr-es202211audio/dsr-es202212audio/vnd.audiokozau

// === skills @921191 ===
n this._inferenceState.getValue()}toolCallUpdates=new H0;trackedFiles=new Mo;discoveredGuidanceFileURIs=new Set;fs;cachedFileChanges=[];disposed$=new H0;isDisposed=!1;shouldContinueAfterRejection=!1;_pendingSkills=new j0([]);handoffState=new j0(void 0);pendingSkills=this._pendingSkills.pipe(f9(),k3({shouldCountRefs:!0}));_awaitingSkillInvocation=new j0([]);toolOrchestrator;currentAgentSpan=null;currentSpan=null;traceStore;constructor(R,T){this.deps=R,this.threadID=T,this.fs=E3R({fileChangeTrackerStorage:this.deps.fileChangeTrackerStorage},this.deps.osFileSystem,T),this.traceStore={startTrace:(a)=>{this.updateThread({type:"trace:start",span:a})},recordTraceEvent:(a,e)=>{this.updateThread({type:"trace:event",span:a,event:e})},recordTraceAttributes:(a,e)=>{this.updateThread({type:"trace:attri

// === skills @921244 ===
 H0;trackedFiles=new Mo;discoveredGuidanceFileURIs=new Set;fs;cachedFileChanges=[];disposed$=new H0;isDisposed=!1;shouldContinueAfterRejection=!1;_pendingSkills=new j0([]);handoffState=new j0(void 0);pendingSkills=this._pendingSkills.pipe(f9(),k3({shouldCountRefs:!0}));_awaitingSkillInvocation=new j0([]);toolOrchestrator;currentAgentSpan=null;currentSpan=null;traceStore;constructor(R,T){this.deps=R,this.threadID=T,this.fs=E3R({fileChangeTrackerStorage:this.deps.fileChangeTrackerStorage},this.deps.osFileSystem,T),this.traceStore={startTrace:(a)=>{this.updateThread({type:"trace:start",span:a})},recordTraceEvent:(a,e)=>{this.updateThread({type:"trace:event",span:a,event:e})},recordTraceAttributes:(a,e)=>{this.updateThread({type:"trace:attributes",span:a,attributes:e})},endTrace:(a)=>{this.upd

// === skills @921264 ===
 Mo;discoveredGuidanceFileURIs=new Set;fs;cachedFileChanges=[];disposed$=new H0;isDisposed=!1;shouldContinueAfterRejection=!1;_pendingSkills=new j0([]);handoffState=new j0(void 0);pendingSkills=this._pendingSkills.pipe(f9(),k3({shouldCountRefs:!0}));_awaitingSkillInvocation=new j0([]);toolOrchestrator;currentAgentSpan=null;currentSpan=null;traceStore;constructor(R,T){this.deps=R,this.threadID=T,this.fs=E3R({fileChangeTrackerStorage:this.deps.fileChangeTrackerStorage},this.deps.osFileSystem,T),this.traceStore={startTrace:(a)=>{this.updateThread({type:"trace:start",span:a})},recordTraceEvent:(a,e)=>{this.updateThread({type:"trace:event",span:a,event:e})},recordTraceAttributes:(a,e)=>{this.updateThread({type:"trace:attributes",span:a,attributes:e})},endTrace:(a)=>{this.updateThread({type:"tra

// === skills @927261 ===
kipping ${R.type} - signal aborted.`,{name:"handle queue",threadID:this.threadID});return}if(await this.resume(),this.handleCalled=!0,await this.acquireThread(),R.type==="pending-skills"){let r=this._pendingSkills.getValue();this._pendingSkills.next([...r,...R.skills]),Z.info("Pending skills set for injection",{threadID:this.threadID,skillNames:R.skills.map((h)=>h.name)});return}let a=R,e=[];if(R.type==="user:message"){let r=await NDT(R.message,{configService:this.deps.configService,filesystem:this.fs.fileSystem}),h=(await this.getConfig(T)).settings["experimental.autoSnapshot"]??!1,t=[];if(h){let i=this.thread.nextMessageId??0,c=await this.getWorkspaceRoot(T??new AbortController().signal),{createSnapshots:o}=await Promise.resolve().then(()=>(VbR(),SX));t=await o(c?[c]:[],this.threadID,i)}

// === skills @927292 ===
ted.`,{name:"handle queue",threadID:this.threadID});return}if(await this.resume(),this.handleCalled=!0,await this.acquireThread(),R.type==="pending-skills"){let r=this._pendingSkills.getValue();this._pendingSkills.next([...r,...R.skills]),Z.info("Pending skills set for injection",{threadID:this.threadID,skillNames:R.skills.map((h)=>h.name)});return}let a=R,e=[];if(R.type==="user:message"){let r=await NDT(R.message,{configService:this.deps.configService,filesystem:this.fs.fileSystem}),h=(await this.getConfig(T)).settings["experimental.autoSnapshot"]??!1,t=[];if(h){let i=this.thread.nextMessageId??0,c=await this.getWorkspaceRoot(T??new AbortController().signal),{createSnapshots:o}=await Promise.resolve().then(()=>(VbR(),SX));t=await o(c?[c]:[],this.threadID,i)}if(e=this._pendingSkills.getVal

// === skills @927872 ===
.thread.nextMessageId??0,c=await this.getWorkspaceRoot(T??new AbortController().signal),{createSnapshots:o}=await Promise.resolve().then(()=>(VbR(),SX));t=await o(c?[c]:[],this.threadID,i)}if(e=this._pendingSkills.getValue(),e.length>0)Z.info("Pending skills will be injected as info message",{threadID:this.threadID,skillNames:e.map((i)=>i.name)}),this._pendingSkills.next([]);a=Dr(R,(i)=>{if(i.message=O8(r.message),t.length>0){if(!i.message.userState)i.message.userState=O8({currentlyVisibleFiles:[]});i.message.userState.snapshotOIDs=O8(t)}T?.throwIfAborted()})}if(a.type==="assistant:message"||a.type==="assistant:message-update")a=this.addNormalizedInputToToolUses(a);try{if(this.ephemeralError.getValue()!==void 0)this.ephemeralError.next(void 0);let r=this.thread;if(this.updateThread(a),this

// === skills @928027 ===
await o(c?[c]:[],this.threadID,i)}if(e=this._pendingSkills.getValue(),e.length>0)Z.info("Pending skills will be injected as info message",{threadID:this.threadID,skillNames:e.map((i)=>i.name)}),this._pendingSkills.next([]);a=Dr(R,(i)=>{if(i.message=O8(r.message),t.length>0){if(!i.message.userState)i.message.userState=O8({currentlyVisibleFiles:[]});i.message.userState.snapshotOIDs=O8(t)}T?.throwIfAborted()})}if(a.type==="assistant:message"||a.type==="assistant:message-update")a=this.addNormalizedInputToToolUses(a);try{if(this.ephemeralError.getValue()!==void 0)this.ephemeralError.next(void 0);let r=this.thread;if(this.updateThread(a),this.onThreadDelta(a,r),e.length>0)await this.injectPendingSkills(e,T)}catch(r){if(!uh(r))Z.error("Ephemeral error during handle processing",r,{name:"ThreadWor

// === skills @948742 ===
catch((r)=>{Z.error("Auto-retry failed",{error:r})});else this.retryCountdownSeconds.next(e)},1000)}addPendingSkill(R){Z.debug("addPendingSkill",{threadID:this.threadID,skillName:R.name});let T=this._pendingSkills.getValue();if(!T.some((a)=>a.name===R.name))this._pendingSkills.next([...T,R])}removePendingSkill(R){Z.debug("removePendingSkill",{threadID:this.threadID,skillName:R});let T=this._pendingSkills.getValue();this._pendingSkills.next(T.filter((a)=>a.name!==R))}clearPendingSkills(){Z.debug("clearPendingSkills",{threadID:this.threadID}),this._pendingSkills.next([])}getPendingSkills(){return this._pendingSkills.getValue()}setTestEphemeralError(R){this.ephemeralError.next(R)}trackFiles(R){for(let T of R)this.trackedFiles.add(T)}async restoreFileChangesFromBackups(){try{let R=await this.f

// === skills @948806 ===
etryCountdownSeconds.next(e)},1000)}addPendingSkill(R){Z.debug("addPendingSkill",{threadID:this.threadID,skillName:R.name});let T=this._pendingSkills.getValue();if(!T.some((a)=>a.name===R.name))this._pendingSkills.next([...T,R])}removePendingSkill(R){Z.debug("removePendingSkill",{threadID:this.threadID,skillName:R});let T=this._pendingSkills.getValue();this._pendingSkills.next(T.filter((a)=>a.name!==R))}clearPendingSkills(){Z.debug("clearPendingSkills",{threadID:this.threadID}),this._pendingSkills.next([])}getPendingSkills(){return this._pendingSkills.getValue()}setTestEphemeralError(R){this.ephemeralError.next(R)}trackFiles(R){for(let T of R)this.trackedFiles.add(T)}async restoreFileChangesFromBackups(){try{let R=await this.fs.tracker.restoreFromBackups();Z.debug(`Restored ${R.totalBackup

// === skills @948936 ===
this._pendingSkills.getValue();if(!T.some((a)=>a.name===R.name))this._pendingSkills.next([...T,R])}removePendingSkill(R){Z.debug("removePendingSkill",{threadID:this.threadID,skillName:R});let T=this._pendingSkills.getValue();this._pendingSkills.next(T.filter((a)=>a.name!==R))}clearPendingSkills(){Z.debug("clearPendingSkills",{threadID:this.threadID}),this._pendingSkills.next([])}getPendingSkills(){return this._pendingSkills.getValue()}setTestEphemeralError(R){this.ephemeralError.next(R)}trackFiles(R){for(let T of R)this.trackedFiles.add(T)}async restoreFileChangesFromBackups(){try{let R=await this.fs.tracker.restoreFromBackups();Z.debug(`Restored ${R.totalBackups} backup files from disk`),await this.updateFileChanges()}catch(R){Z.error("Error restoring file changes",R,{threadID:this.thread