
// === navigation @1224317: canNavigateBack ===
eject?.(R),this.readyResolve=null,this.readyReject=null}async createThread(){return(await this.waitForAttach()).createThread()}async switchThread(R){return(await this.waitForAttach()).switchThread(R)}canNavigateBack(){return this.attachedPool?.canNavigateBack()??!1}canNavigateForward(){return this.attachedPool?.canNavigateForward()??!1}async navigateBack(){return(await this.waitForAttach()).navigateBack()}async navigateForward(){return(await this.waitForAttach()).navigateForward()}async createHandoff(R,T){return(await this.waitForAttach()).createHandoff(R,T)}async deleteThread(R){let T=await this.waitForAttach();if(T.deleteThread)await T.deleteThread(R)}async dispose(){for(let R of this.atta

// === navigation @1224383: canNavigateForward ===
teThread(){return(await this.waitForAttach()).createThread()}async switchThread(R){return(await this.waitForAttach()).switchThread(R)}canNavigateBack(){return this.attachedPool?.canNavigateBack()??!1}canNavigateForward(){return this.attachedPool?.canNavigateForward()??!1}async navigateBack(){return(await this.waitForAttach()).navigateBack()}async navigateForward(){return(await this.waitForAttach()).navigateForward()}async createHandoff(R,T){return(await this.waitForAttach()).createHandoff(R,T)}async deleteThread(R){let T=await this.waitForAttach();if(T.deleteThread)await T.deleteThread(R)}async dispose(){for(let R of this.attachedPoolSubscriptions)R.unsubscribe();if(this.attachedPoolSubscrip

// === navigation @1224461: navigateBack ===
d(R){return(await this.waitForAttach()).switchThread(R)}canNavigateBack(){return this.attachedPool?.canNavigateBack()??!1}canNavigateForward(){return this.attachedPool?.canNavigateForward()??!1}async navigateBack(){return(await this.waitForAttach()).navigateBack()}async navigateForward(){return(await this.waitForAttach()).navigateForward()}async createHandoff(R,T){return(await this.waitForAttach()).createHandoff(R,T)}async deleteThread(R){let T=await this.waitForAttach();if(T.deleteThread)await T.deleteThread(R)}async dispose(){for(let R of this.attachedPoolSubscriptions)R.unsubscribe();if(this.attachedPoolSubscriptions=[],this.attachedPool)await this.attachedPool.dispose();this.recentThread

// === navigation @1224532: navigateForward ===
(){return this.attachedPool?.canNavigateBack()??!1}canNavigateForward(){return this.attachedPool?.canNavigateForward()??!1}async navigateBack(){return(await this.waitForAttach()).navigateBack()}async navigateForward(){return(await this.waitForAttach()).navigateForward()}async createHandoff(R,T){return(await this.waitForAttach()).createHandoff(R,T)}async deleteThread(R){let T=await this.waitForAttach();if(T.deleteThread)await T.deleteThread(R)}async dispose(){for(let R of this.attachedPoolSubscriptions)R.unsubscribe();if(this.attachedPoolSubscriptions=[],this.attachedPool)await this.attachedPool.dispose();this.recentThreadIDsSubject.complete(),this.threadTitlesSubject.complete(),this.threadHa

// === threadWorker @951966 ===
>e.name)}),this.thread=T}async executeHandoff(R){Z.info("Executing handoff",{threadID:this.threadID,goal:R}),this.handoffState.next({goal:R});try{let{threadWorkerService:T}=await Promise.resolve().then(()=>(hA(),AWR)),a={toolService:this.deps.toolService,configService:this.deps.configService,skillService:this.deps.skillService,getThreadEnvironment:this.deps.getThreadEnvironment,filesystem:this.fs.fileSystem,threadService:this.deps.threadService},{threadID:e}=await T.handoff(this.deps,{threadID:this.threadID,goal:R,images:[],mode:"initial",agentMode:this.thread.agentMode,queuedMessages:this.thread.queuedMessages,clearQueuedMessages:!0,blockInd

// === threadWorker @924643 ===
state:R})),k3({shouldCountRefs:!0}));threadReadWriter=null;get thread(){if(!this.threadReadWriter)throw Error(`thread read-writer not initialized for ThreadWorker: ${this.threadID}`);return this.threadReadWriter.read()}set thread(R){if(!this.threadReadWriter)throw Error(`thread read-writer not initialized for ThreadWorker: ${this.threadID}`);this.threadReadWriter.write(R),this.__testing__setThread(R)}updateThread(R){if(!this.threadReadWriter)throw Error(`thread read-writer not initialized for ThreadWorker: ${this.threadID}`);this.threadReadWriter.update(fIT(R,new Date)),this.__testing__setThread(this.threadReadWriter.read())}async acquireThre

// === threadWorker @954721 ===
.every((t)=>{let i=h.get(t);if(!i||i.run.status!=="done")return!1;return i.run.isFinal===!0}))return!1;return!0}class yWR{threadWorkers=new kOR;async getOrCreateForThread(R,T){let a=this.threadWorkers.get(T);if(!a){if(a=new aj(R,T),this.threadWorkers.set(T,a),this.threadWorkers.size>25)Z.info("Many active thread workers detected",{name:"ThreadWorkerService.memoryCheck",threadID:T,totalWorkerCount:this.threadWorkers.size})}return cL.record(this.threadWorkers.size),a}async createThreadWorker(R,T){let a=await this.getOrCreateForThread(R,T);return await a.resume(),a}async seedThreadMessages(R,T,a,e){let r=await R.threadService.exclusiveSyncReadWr

// === thread visibility @1267296 ===
n dZR(R,T,a){await R.validateThreadOwnership?.(T,a);let e=await R.threadService.get(T)??void 0;return uZR(R.workerDeps,{threadID:T,threadMeta:R.switchThreadVisibility?fC(R.switchThreadVisibility):void 0,agentMode:e?void 0:R.switchThreadAgentMode,thread:e,onFirstAssistantMessage:R.onFirstAssistantMessage})}async function l40(R,T,a){let e=T?await dZR(R,T,{nonBlockingOwnershipCheck:a?.nonBlockingOwnershipCheck??!1}):await R.createThread();return new ThR(R,e)}class ThR{deps;queueOnSubmitByDefault=!1;restoreTo=this.truncateThread.bind(this);stateTra

// === MCP @5154716 ===
deepReasoningEffortSubscription=null;anthropicSpeedSubscription=null;openAISpeedSubscription=null;sessionState=Vx;isShowingConsoleOverlay=!1;isShowingMCPStatusModal=!1;isShowingConfirmationOverlay=!1;isShowingFileChangesOverlay=!1;isShowingContextDetailOverlay=!1;threadCostInfo=void 0;threadCostInfoThreadID=void 0;lastInferenceState=void 0;elapsedTimeTimer=null;confirmationOverlayContent="";exitConfirmTimeout=null;clearInputConfirmTimeout=null;cancelProcessingConfirmTimeout=null;historyIndex=-1;historyDraft=null;bashInvocations=[];pendingBashInvocations=new Map;bashInvocationShownAt=new Map;bashInvocationRemoveTimers=new Map;currentTitle=void

// === MCP @5154716 ===
deepReasoningEffortSubscription=null;anthropicSpeedSubscription=null;openAISpeedSubscription=null;sessionState=Vx;isShowingConsoleOverlay=!1;isShowingMCPStatusModal=!1;isShowingConfirmationOverlay=!1;isShowingFileChangesOverlay=!1;isShowingContextDetailOverlay=!1;threadCostInfo=void 0;threadCostInfoThreadID=void 0;lastInferenceState=void 0;elapsedTimeTimer=null;confirmationOverlayContent="";exitConfirmTimeout=null;clearInputConfirmTimeout=null;cancelProcessingConfirmTimeout=null;historyIndex=-1;historyDraft=null;bashInvocations=[];pendingBashInvocations=new Map;bashInvocationShownAt=new Map;bashInvocationRemoveTimers=new Map;currentTitle=void

// === MCP @897103 ===
sync function vf(R,T,{enableTaskList:a,enableTask:e,enableOracle:r,enableDiagnostics:h,enableChart:t=!0},{model:i,provider:c,agentMode:o},C){if(sDT(R.serverStatus))a=!0;let g=Boolean(T.mainThreadID),l=await y0(g?R.toolService.getToolsForMode(o,g):R.toolService.getTools(o),C),n=await Promise.all(l.filter(({enabled:s})=>s).filter(({spec:s})=>a||s.name!==fb).filter(({spec:s})=>e||s.name!==rr).filter(({spec:s})=>r||s.name!==Tr).filter(({spec:s})=>t||s.name!==s7).map(async({spec:s})=>{if(s.name===lc)return f7T(s,R.skillService);return s}));if(c==="openai"){let s=new Set(T.activatedSkills?.map((m)=>m.name)??[]);if(s.size>0){let m=new Set(n.map((v)=

// === news @5160203 ===
ll;threadTitles={};activeThreadSubscription=null;legacyHandoffNavigationSubscription=null;pluginCommands=[];pluginCommandsSubscription=null;async initNewsFeed(){let R=async(a)=>{return xi(a,void 0,this.widget.dependencies.configService)},T=RB0();this.newsFeedReader=new vJR(T,R,"/news.rss"),this.newsFeedSubscription=this.newsFeedReader.stream().subscribe({next:(a)=>{if(a.length>0)this.setState(()=>{this.newsFeedEntries=[...a,...this.newsFeedEntries]})},error:(a)=>{Z.error("News feed error:",a)}})}navigateBack=async()=>{await this.widget.dependen

// === cost @5154836 ===
ShowingConfirmationOverlay=!1;isShowingFileChangesOverlay=!1;isShowingContextDetailOverlay=!1;threadCostInfo=void 0;threadCostInfoThreadID=void 0;lastInferenceState=void 0;elapsedTimeTimer=null;confirmationOverlayContent="";exitConfirmTimeout=null;clearInputConfirmTimeout=null;cancelProcessingConfirmTimeout=null;historyIndex=-1;historyDraft=null;bashInvocations=[];pendingBashInvocations=new Map;bashInvocationShownAt=new Map;bashInvocationRemoveTimers=new Map;currentTitle=void 0;currentShellModeS

// === autoCopy @4918354 ===
wordDragBaseRange=null,this._didMouseMove=!1,this._releaseGlobalMouse(),R||T==="word")this._scheduleAutoCopy()}async _autoCopySelection(){if(!this.widget.copyOnSelectionEnabled)return;let R=this.widget.controller.selectedText;if(R&&R.length>0){let T=!1;try{T=await this.widget.clipboard.writeText(R)}catch(a){Z.debug("Failed to write selection to clipboard:",a)}this._startCopyHighlight(),this.widget.onCopy?.(R,T)}}_scheduleAutoCopy(){this._clearAutoCopyTimer(),this._autoCopyTimer=setTimeout(()=>{t

// === autoCopy @4862359 ===
uper()}};dY=class dY extends w3{constructor(){super()}};hT();M8=class M8 extends FT{focusNode;child;autofocus;canRequestFocus;skipTraversal;onKey;onPaste;onFocusChange;debugLabel;constructor({key:R,focusNode:T,child:a,autofocus:e=!1,canRequestFocus:r=!0,skipTraversal:h=!1,onKey:t,onPaste:i,onFocusChange:c,debugLabel:o}){super({key:R});this.focusNode=T,this.child=a,this.autofocus=e,this.canRequestFocus=r,this.skipTraversal=h,this.onKey=t||null,this.onPaste=i||null,this.onFocusChange=c||null,this.

// === density @4186293 ===
1]===70&&aR[2]===73&&aR[3]===70&&aR[4]===0)f={version:{major:aR[5],minor:aR[6]},densityUnits:aR[7],xDensity:aR[8]<<8|aR[9],yDensity:aR[10]<<8|aR[11],thumbWidth:aR[12],thumbHeight:aR[13],thumbData:aR.subarray(14,14+3*aR[12]*aR[13])}}if(V===65505){if(aR[0]===69&&aR[1]===120&&aR[2]===105&&aR[3]===102&&aR[4]===0)this.exifBuffer=aR.subarray(5,aR.length)}if(V===65518){if(aR[0]===65&&aR[1]===100&&aR[2]===111&&aR[3]===98&&aR[4]===101&&aR[5]===0)v={version:aR[6],flags0:aR[7]<<8|aR[8],flags1:aR[9]<<8|aR[1

// === density @5230544 ===
olProgressByToolUseID:new Map,controller:this.threadPreviewController.scrollController,autofocus:!1,denseView:Hl(MR.agentMode),hasStartedStreamingResponse:_q0(MR),focusNode:new g8({debugLabel:"PreviewFocus"}),onShowImagePreview:()=>{},stateController:this.previewMessageViewController,submitOnEnter:this.submitOnEnter,isDTWMode:I}),_=this.previewThread,j=_?_.messages.length>2000?new IT({mainAxisSize:"max",children:[new $0({child:new FR}),new xT({padding:RT.all(2),child:new B0({child:new pR({text:n